// default package
// Generated 5 juil. 2017 22:43:03 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Combinaison generated by hbm2java
 */
@Entity
@Table(name = "combinaison", catalog = "hackathon_server")
public class Combinaison implements java.io.Serializable {

	private Integer id;
	private String couleurs;

	public Combinaison() {
	}

	public Combinaison(String couleurs) {
		this.couleurs = couleurs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "couleurs", nullable = false, length = 30)
	public String getCouleurs() {
		return this.couleurs;
	}

	public void setCouleurs(String couleurs) {
		this.couleurs = couleurs;
	}

}
