// default package
// Generated 5 juil. 2017 22:43:03 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Objectif generated by hbm2java
 */
@Entity
@Table(name = "objectif", catalog = "hackathon_server")
public class Objectif implements java.io.Serializable {

	private Integer idObjectif;
	private Utilisateur utilisateur;
	private String nomObjectif;
	private String description;
	private char type;
	private float realise;

	public Objectif() {
	}

	public Objectif(Utilisateur utilisateur, String nomObjectif, char type, float realise) {
		this.utilisateur = utilisateur;
		this.nomObjectif = nomObjectif;
		this.type = type;
		this.realise = realise;
	}

	public Objectif(Utilisateur utilisateur, String nomObjectif, String description, char type, float realise) {
		this.utilisateur = utilisateur;
		this.nomObjectif = nomObjectif;
		this.description = description;
		this.type = type;
		this.realise = realise;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_objectif", unique = true, nullable = false)
	public Integer getIdObjectif() {
		return this.idObjectif;
	}

	public void setIdObjectif(Integer idObjectif) {
		this.idObjectif = idObjectif;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_utilisateur", nullable = false)
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "nom_objectif", nullable = false, length = 50)
	public String getNomObjectif() {
		return this.nomObjectif;
	}

	public void setNomObjectif(String nomObjectif) {
		this.nomObjectif = nomObjectif;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "type", nullable = false, length = 1)
	public char getType() {
		return this.type;
	}

	public void setType(char type) {
		this.type = type;
	}

	@Column(name = "realise", nullable = false, precision = 12, scale = 0)
	public float getRealise() {
		return this.realise;
	}

	public void setRealise(float realise) {
		this.realise = realise;
	}

}
