// default package
// Generated 5 juil. 2017 22:43:03 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", catalog = "hackathon_server")
public class Utilisateur implements java.io.Serializable {

	private Integer id;
	private String idFacebook;
	private Set objectifs = new HashSet(0);

	public Utilisateur() {
	}

	public Utilisateur(String idFacebook) {
		this.idFacebook = idFacebook;
	}

	public Utilisateur(String idFacebook, Set objectifs) {
		this.idFacebook = idFacebook;
		this.objectifs = objectifs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "id_facebook", nullable = false, length = 30)
	public String getIdFacebook() {
		return this.idFacebook;
	}

	public void setIdFacebook(String idFacebook) {
		this.idFacebook = idFacebook;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set getObjectifs() {
		return this.objectifs;
	}

	public void setObjectifs(Set objectifs) {
		this.objectifs = objectifs;
	}

}
